export enum STATUS {
  NOT_INITIALIZED = 'NOT_INITIALIZED',
  LOADING_COPIES_FROM_DB = 'LOADING_COPIES_FROM_DB',
  LOADED_COPIES_FROM_DB = 'LOADED_COPIES_FROM_DB',
  LOADING_STRATEGY_FROM_DB = 'LOADING_STRATEGY_FROM_DB',
  LOADED_STRATEGY_FROM_DB = 'LOADED_STRATEGY_FROM_DB',
  LOADING_TARGETS_FROM_DB = 'LOADING_TARGETS_FROM_DB',
  LOADEDED_TARGETS_FROM_DB = 'LOADEDED_TARGETS_FROM_DB',
  LOADING_REMOTE_TARGETS = 'LOADING_REMOTE_TARGETS',
  LOADED_REMOTE_TARGETS = 'LOADED_REMOTE_TARGETS',
  LOADED_TARGET_POSITIONS = 'LOADED_TARGET_POSITIONS',
  ERROR = 'ERRORED',
}
